### ISSUE TITLE
Package name should not contain "-_rust"

### ISSUE THREAD

**Issue by theduke** [ynqa/kubernetes-rust#3]
Hey there.

Package names (Cargo.toml) should never contain "-rust" or "_rust".
They are totally redundant and pretty annoying for users.

**Comment by ynqa** [comment]
Thanks for your pointing. Sure, I'll remove the suffix later.

**Comment by ynqa** [comment]
@theduke Thanks for your pointing. I'll remove the suffix later.

**Comment by ynqa** [comment]
Dealt with this issue.
